---
- name: Configure Docker and K8s on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: updating apt
      command: sudo apt-get update
    - name: Install Docker
      command: sudo apt-get install -y docker.io
      become: yes
      become_user: root
    - name: Start Docker Service
      command: sudo systemctl start docker
      become: yes
      become_user: root
    - name: Deploy Docker Container
      command: docker run -itd -p 8084:8082 nikhillara1989/final_health_care:1.0
- name: Install Kubernetes on Ubuntu EC2 instance
  hosts: All
  become: true
  connection: ssh
  tasks:
    - name:
        apt:
          update_cache: yes
          cache_valid_time: 3600
          name:
            - apt-transport-https
            - ca-certificates
            - curl
            - software-properties-common
    - name:
        shell: >
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg |
          apt-key add -
    - name:
        apt_repository:
          repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
          state: present
    - name:
        apt:
          update_cache: yes
    - name:
        apt:
          name:
            - kubectl
            - kubelet
            - kubeadm
    - name:
        shell: kubeadm init --pod-network-cidr=10.244.0.0/16
    - name:
        shell: kubeadm join --token {{ ansible_host_token }}
          --discovery-token-ca-cert-hash {{
          ansible_host_discovery_token_ca_cert_hash }} https://{{ ansible_host
          }}:6443
    - name:
        shell: |
          mkdir -p ~/.kube
          cp /etc/kubernetes/admin.conf ~/.kube/config
          chown $(id -u):$(id -g) ~/.kube/config
