- name: Configure Docker and K8s on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update package lists
      apt: update_cache=yes

    - name: Install Ansible
      apt:
        name: ansible
        state: present
        
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker Container
      docker_container:
        name: health_care
        image: nikhillara1989/final_health_care:1.0
        state: started
        ports:
          - "8084:8082"

- name: Setup Kubernetes Cluster
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
        state: present

    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

- name: Initialize Kubernetes Master
  hosts: master
  become: yes
  tasks:
    - name: Initialize Kubernetes cluster
      command: kubeadm init --apiserver-advertise-address=<master_private_ip> --pod-network-cidr=192.168.0.0/16
      register: init_output

    - name: Set up kubeconfig for root
      command: "{{ item }}"
      with_items:
        - mkdir -p $HOME/.kube
        - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        - chown $(id -u):$(id -g) $HOME/.kube/config
      when: init_output.changed

    - name: Install Calico network plugin
      command: kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml
      when: init_output.changed

- name: Join Worker Nodes to Cluster
  hosts: workers
  become: yes
  tasks:
    - name: Join Kubernetes cluster
      command: kubeadm join <master_private_ip>:6443 --token <token> --discovery-token-ca-cert-hash sha256:<hash>

