apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: health-care-k8s-deployment
spec:
  selector:
    matchLabels:
      app: health-care-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: health-care-k8s
    spec:
      containers:
        - name: health-care-k8s
          image: nikhillara1989/final_health_care:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: healthcare-k8ssvc
spec:
  selector:
    app: health-care-k8s
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
      nodeport: 30500
  type: NodePort # type of the service.
