apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-care-k8s-deployment
spec:
  selector:
    matchLabels:
      app: health-care-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: health-care-k8s
    spec:
      containers:
      - name: health-care-k8s
        image: nikhillara1989/final_health_care:1.0
        imagepullpolicy: IfNotPresent
        ports:
          - containerPort: 8070

---

apiVersion: v1
kind: Service
metadata: 
  name: health-care-k8ssvc
spec:
  selector:
    app: health-care-k8s
  ports:
    - protocol: "TCP"
      port: 8070
      targetport: 8070
      nodeport: 32500
  type: NodePort
      
